name: flutter_mining_app
description: "Eine Flutter Mining App mit AdMob und PayPal-Integration."

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^3.1.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
